import { getShopRepository } from "@/lib/shop-repository";

export const dynamic = "force-dynamic";

type Props = {
  searchParams: Promise<{ ran?: string }>;
};

export default async function WarehousePage({ searchParams }: Props) {
  const repo = getShopRepository();
  const params = await searchParams;
  const queue = await repo.getPriorityQueue();
  const predictions = await repo.getPipelinePredictions();
  const lastScoringRunAt = await repo.getLastScoringRunAt();
  const justRan = params.ran === "1";

  return (
    <section className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-2xl font-semibold">Late Delivery Priority Queue</h2>
          <p className="text-sm text-slate-600">
            Top 50 orders by predicted late-delivery probability.
          </p>
        </div>
        <form action="/api/scoring/run" method="POST">
          <button
            className="rounded bg-slate-900 px-3 py-2 text-sm text-white hover:bg-slate-700"
            type="submit"
          >
            Run Scoring
          </button>
        </form>
      </div>

      {justRan ? (
        <p className="rounded border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800">
          Scoring job completed and queue refreshed.
        </p>
      ) : null}

      <article className="rounded border border-slate-200 bg-white p-4">
        <h3 className="text-lg font-semibold">Queue Results</h3>
        <p className="mb-3 text-sm text-slate-600">
          Last scoring run: {lastScoringRunAt ? new Date(lastScoringRunAt).toLocaleString() : "Not run yet"}
        </p>
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead>
              <tr className="border-b border-slate-200 text-slate-600">
                <th className="px-2 py-2">Order ID</th>
                <th className="px-2 py-2">Customer ID</th>
                <th className="px-2 py-2">Total</th>
                <th className="px-2 py-2">Late Delivery Probability</th>
              </tr>
            </thead>
            <tbody>
              {queue.map((order) => (
                <tr className="border-b border-slate-100" key={order.id}>
                  <td className="px-2 py-2">#{order.id}</td>
                  <td className="px-2 py-2">{order.customerId}</td>
                  <td className="px-2 py-2">${order.totalAmount.toFixed(2)}</td>
                  <td className="px-2 py-2">{(order.lateDeliveryProbability * 100).toFixed(1)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </article>

      <article className="rounded border border-slate-200 bg-white p-4">
        <h3 className="text-lg font-semibold">Pipeline Prediction Output</h3>
        <p className="mb-3 text-sm text-slate-600">
          This section displays the latest predictions generated by the scoring pipeline.
        </p>
        {predictions.length === 0 ? (
          <p className="text-sm text-slate-600">No prediction output yet. Run scoring to generate results.</p>
        ) : (
          <ul className="space-y-1 text-sm">
            {predictions.slice(0, 10).map((prediction) => (
              <li key={prediction.orderId}>
                Order #{prediction.orderId}: {(prediction.lateDeliveryProbability * 100).toFixed(1)}%
              </li>
            ))}
          </ul>
        )}
      </article>
    </section>
  );
}
