create table if not exists public.customers (
  customer_id bigint primary key,
  full_name text,
  email text,
  gender text,
  birthdate text,
  created_at text,
  city text,
  state text,
  zip_code text,
  customer_segment text,
  loyalty_tier text,
  is_active integer
);

create table if not exists public.orders (
  order_id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(customer_id),
  order_datetime text,
  billing_zip text,
  shipping_zip text,
  shipping_state text,
  payment_method text,
  device_type text,
  ip_country text,
  promo_used integer,
  promo_code text,
  order_subtotal double precision,
  shipping_fee double precision,
  tax_amount double precision,
  order_total double precision,
  risk_score double precision,
  is_fraud integer,
  fraud_probability double precision,
  predicted_fraud integer,
  fraud_scored_at timestamptz
);

create table if not exists public.shipments (
  shipment_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id),
  ship_datetime text,
  carrier text,
  shipping_method text,
  distance_band text,
  promised_days integer,
  actual_days integer,
  late_delivery integer
);

create table if not exists public.scoring_runs (
  run_id bigint generated by default as identity primary key,
  scored_at timestamptz not null default now()
);

create table if not exists public.order_scores (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id),
  late_delivery_probability double precision not null,
  scored_at timestamptz not null default now()
);

create index if not exists idx_orders_customer_id on public.orders(customer_id);
create index if not exists idx_orders_risk_score on public.orders(risk_score desc);
create index if not exists idx_order_scores_scored_at on public.order_scores(scored_at desc);
